version: '3'

services:
    dev-db:
        build: ./database
        networks:
          - dev-dbnet
        ports:
          - 5432:5432
        environment:
          - POSTGRES_USER=transient
          - POSTGRES_PASSWORD=password
        restart: always

    dev-backend:
        build: ./backend
        ports:
          - 3000:3001
        networks:
          - dev-dbnet
        volumes:
          - ./backend:/src
        depends_on:
          - dev-db

    dev-recommends:
        build: ./recommends
        ports:
          - 4000:4001
        networks:
          - dev-dbnet
        volumes:
          - ./recommends:/src
        depends_on:
          - dev-db

    dev-frontend:
        build: ./frontend
        ports:
          - 8080:8080
        volumes:
          - ./frontend/etc:/src/etc
          - ./frontend/public:/src/public
          - ./frontend/src:/src/src
          - ./frontend/package.json:/src/package.json
          - node_modules:/src/node_modules
        command: sh -c "cd src && npm install && npm run serve"
        depends_on:
          - dev-backend

    dev-nginx:
        build: ./nginx
        restart: always
        network_mode: "host"
        depends_on:
          - dev-backend
          - dev-frontend

volumes:
    node_modules:

networks:
    dev-dbnet:
