version: '3'

services:
    db:
        build: ./database
        restart: always

    dev-backend:
        build: ./backend
        ports:
          - 3000:3001
        volumes:
          - ./backend:/src
        depends_on:
          - db

    dev-frontend:
        build: ./frontend
        ports:
          - 8080:8080
        volumes:
          - ./frontend/etc:/src/etc
          - ./frontend/public:/src/public
          - ./frontend/src:/src/src
          - ./frontend/package.json:/src/package.json
          - node_modules:/src/node_modules
        command: sh -c "cd src && npm install && npm run serve"
        depends_on:
          - dev-backend

    nginx:
        build: ./nginx
        restart: always
        network_mode: "host"
        depends_on:
          - dev-backend
          - dev-frontend

volumes:
    node_modules:
