version: '3'

services:
    nginx:
        build: ./nginx
        restart: always
        network_mode: "host"

    dev-frontend:
        image: node:8.0.0-alpine
        ports:
          - 8080:8080
        volumes:
          - ./frontend:/src
          - node_modules:/src/node_modules
        command: sh -c "cd src &&  npm install && npm run serve"

    dev-backend:
        build: ./backend
        ports:
          - 3000:3000

volumes:
    node_modules:
